default: &default
  timeout: 5000

development:
  <<: *default
  ftp_ip: 10.126.41.144
  port: 18522
  username: shzh
  password: shzh@0418
  upload_dir: fct2ap
  download_dir: ap2fct
  jbda_dir: JDBSupload/POST
  jbda_repost_dir: JDBSupload/REPOST
  jd_dir: JDSHupload
  jbda_bank_dir: JDBSupload/SQJBD
test:
  <<: *default
  ftp_ip: 10.126.41.144
  port: 18522
  username: shzh
  password: shzh@0418
  upload_dir: fct2ap
  download_dir: ap2fct
  jbda_dir: JDBSupload/POST
  jbda_repost_dir: JDBSupload/REPOST
  jd_dir: JDSHupload
  jbda_bank_dir: JDBSupload/SQJBD
production:
  <<: *default
  ftp_ip: 10.126.41.144
  port: 18522
  username: shzh
  password: '@Flzx3qc'
  upload_dir: fct2ap
  download_dir: ap2fct
  jbda_dir: JDBSupload/POST
  jbda_repost_dir: JDBSupload/REPOST
  jd_dir: JDSHupload
  jbda_bank_dir: JDBSupload/SQJBD