default: &default
  timeout: 5000

development:
  <<: *default
  ftp_ip: 10.126.41.144
  username: shzh
  password: shzh@0418
  upload_dir: fct2ap
  download_dir: ap2fct
  jbda_dir: JDBSupload
  jbda_dir: JDBSupload
test:
  <<: *default
  ftp_ip: 10.126.41.144
  username: shzh
  password: shzh@0418
  upload_dir: fct2ap
  download_dir: ap2fct
  jbda_dir: JDBSupload
production:
  <<: *default
  ftp_ip: 10.126.41.144
  username: shzh
  password: shzh@0418
  upload_dir: fct2ap
  download_dir: ap2fct
  jbda_dir: JDBSupload
  jd_dir: JDSHupload