default: &default
  timeout: 5000

development:
  <<: *default
  # order create
  order_create_url: http://10.126.22.218:9080/xyd_server/OrderCreateServlet
  oc_system_name: test
  oc_pwd: "11111"
  ecCompanyId: 
  parentId: 
  logistics_provider: B
  ecommerce_no: XYD
  inner_channel: "0"
  sender_no: "1030001504969"
  # sy_sender_no:
  # gy_sender_no:
  base_product_no_1: "1" #寄付
  base_product_no_3: "3" #到付
  payment_mode_2: "2"
  # address parsing
  address_parsing_url: http://10.126.22.218:9080/xyd_server/AddressParsingServlet
  ap_system_name: test
  ap_pwd: "11111"
  ap_salt: ""
  order_create_by_waybill_no_url: http://10.126.22.218:9080/xyd_server/OrderCreateByWaybillNoServlet
test:
  <<: *default
  # order create
  order_create_url: http://10.126.22.218:9080/xyd_server/OrderCreateServlet
  oc_system_name: test
  oc_pwd: "11111"
  ecCompanyId: 
  parentId: 
  logistics_provider: B
  ecommerce_no: HNHCYY
  inner_channel: "0"
  sender_no: "1030001504969"
  # sy_sender_no:
  # gy_sender_no:
  base_product_no_1: "1" #寄付
  base_product_no_3: "3" #到付
  payment_mode_2: "2"
  # address parsing
  address_parsing_url: http://10.126.22.218:9080/xyd_server/AddressParsingServlet
  ap_system_name: test
  ap_pwd: "11111"
  ap_salt: ""
  order_create_by_waybill_no_url: http://10.126.25.218:7001/xyd_server/OrderCreateByWaybillNoServlet
production:
  <<: *default
  # order create
  #order_create_url: http://172.20.7.11:3000/xyd_server/OrderCreateServlet
  order_create_url: http://10.126.25.138:7001/xyd_server/OrderCreateServlet
  oc_system_name: syhs2022
  oc_pwd: M3Q5NGREcjB0NE9zOCk5
  ecCompanyId: SHYIYAO
  parentId: b2aaZH1Cnjf8D
  logistics_provider: B
  ecommerce_no: SHYIYAO
  inner_channel: "0"
  sender_no: "1030001504969"
  # sy_sender_no: "1030001771000"
  # gy_sender_no: "1100128414327"
  base_product_no_1: "1" #寄付
  base_product_no_3: "3" #到付
  payment_mode_2: "2"
  # address parsing
  #address_parsing_url: http://172.20.7.11:3000/xyd_server/AddressParsingServle
  address_parsing_url: http://10.126.25.138:7001/xyd_server/AddressParsingServlet
  ap_system_name: syhs2022
  ap_pwd: c2h5eWFkZHJlc3NwYXJzaW5n
  ap_salt: 23e1691cb0a5e42bd8236b4ea794bf0c
  o#rder_create_by_waybill_no_url: http://172.20.7.11:3000/yd_server/OrderCreateByWaybillNoServlet
  order_create_by_waybill_no_url: http://10.126.25.138:7001/xyd_server/OrderCreateByWaybillNoServlet

